global:
  log_directory: 'retrieved_logs'
  reload_interval: 60
  graph_directory: 'common_path'
log_retriever:
  url: 'INSERT_GRAYLOG_URL_HERE'
  api_token: 'INSERT_API_TOKEN_HERE'
filters:
  'filter_expressions':
    - '^Searching for ASPSPs:'
    - '^(.+) charset will be used for response body parsing$'
tags:
  approach:                         # name of the field the tag gets written to (may be same as source if field value should replace old one)
    source: 'message'               # field that gets matched to determine the tag value
    tag_all: true                   # whether only the matching entry or all related entries should be tagged
    default_value: 'not available'  # default value that is used if no matching value was found
    mappings:                       # mapping of tag values to their respective keyword(s)
      'embedded':
        - 'approach=EMBEDDED'
      'redirect':
        - 'approach=REDIRECT'
      'OAuth':
        - 'approach=OAUTH'
      'decoupled':
        - 'approach=DECOUPLED'
  method:
    source: 'message'
    tag_all: false
    default_value: 'not available'
    mappings:
      'get_accounts':
        - 'GET_ACCOUNTS'
        - 'get account list'
      'get_transactions':
        - 'GET_TRANSACTIONS'
        - 'get transaction list'

  label:
    source: 'message'
    tag_all: false
    default_value: '_else_'
    mappings:
      'Status 200: OK':
        - 'Status - 200'
        - 'status - 200'
      'Status 201':
        - 'response status - 201'
        - 'Response status - 201'
      'Status 400: Error':
        - 'Status - 400'
        - 'status - 400'
      'Status 401: Error':
        - 'Response status - 401'
        - 'response status - 401'
      'Status 403: Error':
        - 'response status - 403'
        - 'Response status - 403'
      'Status 405: Error':
        - 'code=405'
        - 'Code=405'
      'Consent Invalid':
        - 'CONSENT_INVALID'
      'Bad Request':
        - 'FORMAT_ERROR'
      'Internal Server Error':
        - 'INTERNAL_SERVER_ERROR'
      'PSU Credentials Invalid':
        - 'PSU_CREDENTIALS_INVALID'
      'Create Consent Service Invalid':
        - 'SERVICE_INVALID'
      'Service Unavailable':
        - 'SERVICE_UNAVAILABLE'
      'Processing_error':
        - 'Processing Error'
      'Transaction Status Is ACSP':
        - 'Transaction status is ACSP'
      'ASPSPs Search':
        - 'Searching for ASPSPs'
        - 'searching for ASPSPs'
        - 'Search ASPSPs'
        - 'search ASPSPs'
      'ASPSPs Not Found':
        - 'Aspsp was not found'
        - 'aspsp was not found'
      'Create New Session':
        - 'create a new session'
      'Consent Status Is Valid':
        - 'Consent status is valid'
      'Delete Consent Status':
        - 'Delete consent status'
      'Get Account List':
        - 'get account list'
      'Get Transaction List':
        - 'get transaction list'
      'Load Transactions':
        - 'load transactions'
        - 'Load transactions'
      'No Information About Transactions':
        - 'no information about transactions'
      'Event: ASPSP Found':
        - 'Processing AspspFoundEvent'
        - 'processing AspspFoundEvent'
      'Event: Transactions Received':
        - 'Processing TransactionsReceivedEvent'
        - 'processing TransactionsReceivedEvent'
      'Event:Accounts Found':
        - 'Processing AccountFoundEvent'
        - 'processing AccountFoundEvent'
      'Redirect To Online Banking Page':
        - 'Redirect to online banking page'
      'Redirect From ASPSP':
        - 'redirect from ASPSP'
      'SCA Status Is Finalised':
        - 'status is finalised'
      'Session':
        - 'Session'
      'Server Request (POST)':
        - 'POST'
      'Server Request (PUT)':
        - 'PUT'
      'Server Response 200: OK':
        - 'HTTP/1.1 200'
      'Server Response 201':
        - 'HTTP/1.1 201'
      'Server Response 204':
        - 'HTTP/1.1 204'
      'Show Payment Details':
        - 'show payment details'
      'Show Transactions':
        - 'show transactions'
        - 'Show transactions'
      'slack':
        - 'Slack'
        - 'slack'
      'ASPSP Lookup':
        - 'step=ASPSP_LOOKUP'
      'Authenticate PSU':
        - 'step=AUTHENTICATE_PSU'
      'Create Consent':
        - 'step=CREATE_CONSENT'
      'Get Accounts':
        - 'step=GET_ACCOUNTS'
      'Get Transactions':
        - 'step=GET_TRANSACTIONS'
      'Initiate Payment':
        - 'step=INITIATE_PAYMENT'
      'PSU Redirect':
        - 'step=PSU_REDIRECT'
      'Select Strong Customer Authentication (SCA)':
        - 'step=SELECT_SCA'
      'Send One-Time-Password (OTP)':
        - 'step=SEND_OTP'
      'Update Consent PSU Data':
        - 'update consent PSU data'
      'Warning: Unhandeled Exception':
        - 'Unhandled exception'
        - 'unhandled exception'

  status:
    source: 'label'
    tag_all: true
    default_value: 'aborted'
    mappings:
      'error':
        - 'error'
      'succeed':
        - 'Delete Consent Status'

  errortype:
    source: 'label'
    tag_all: true
    default_value: 'No Error'
    mappings:
      'PSU Credentials Invalid':
        - 'Status 401: Error'
        - 'PSU Credentials Invalid'
      'ASPSPs Not Found':
        - 'ASPSPs Not Found'
      'Create Consent Service Invalid':
        - 'Create Consent Service Invalid'
      'Consent Invalid':
        - 'Consent Invalid'
        - 'Status 403: Error'
      'Internal Server Error':
        - 'Internal Server Error'
      'Service Unavailable':
        - 'Service Unavailable'
      'Bad Request':
        - 'Bad Request'
      'Request Method Not Allowed':
        - 'Status 405: Error'

  bank:
    source: 'message'
    tag_all: true
    default_value: 'not available'
    extractors:
      - bic='(\w+)'
